"use client";
import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets/Header";
import { use } from "react";

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceCodePro.variable} text-sm antialiased flex flex-row justify-center`}>
        <div className="w-full max-w-6xl">
          <Header />
          <div className="p-3">{children}</div>
        </div>
      </body>
    </html>
  );
}
